- name: install unzip
  package: # this module is a generic package manager
    name: unzip

- name: install terraform
  unarchive: # this module requires unzip
    src: https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root
